### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by jimparker96313**
Ian,
  Here are the changes I made to incorporate setuptools with your memory usage tool.

Cheers,
--Jim

### CODE REVIEW

**Comment by ianozsvald** [comment]
Thank you for the patch. I'm running pydatalondon conf in a few days so I'm tied up there, I'll review this next week. Cheers!

**Comment by FrancescAlted** [comment]
Hey, this is cool.  It would be nice to be able to use this so as to publish this awesome small package in the PyPI repository (this is totally interested, as I am planning to use ipython_memory_usage in my forthcoming tutorial in EuroPython).

**Comment by FrancescAlted** [comment]
Maybe this still needs to fille `init__.py` with:

```
from ipython_memory_usage import start_watching_memory, stop_watching_memory
```

and maybe added some other import for `ipython_memory_usage_perf.py`, but just for Linux.

**Comment by jni** [comment]
:+1: ! Can we get this merged ASAP? =)

**Comment by ianozsvald** [comment]
Merged! Many thanks :-) README updated to reflect the package. Many thanks :-)

**Comment by jimparker96313** [comment]
Glad to help.  Cheers.

**Pull request merged**
